name: Playwright Tests (typescript)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-node@v4.1.0
    - name: Install dependencies
      run: npm ci
      working-directory: ./typescript
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ./typescript
    - name: Run Playwright tests
      run: npx playwright test
      working-directory: ./typescript
    - uses: actions/upload-artifact@v4.4.3
      if: always()
      with:
        name: playwright-report
        path: ./typescript/playwright-report/
        retention-days: 30
